# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import off_django.models_extensions


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OFFFood',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
                ('creator', models.TextField(default=None, null=True)),
                ('created_t', models.IntegerField(default=None, null=True)),
                ('created_datetime', models.DateTimeField(default=None, null=True)),
                ('last_modified_t', models.IntegerField(default=None, null=True)),
                ('last_modified_datetime', models.DateTimeField(default=None, null=True)),
                ('product_name', models.TextField(default=None, null=True)),
                ('generic_name', models.TextField(default=None, null=True)),
                ('quantity', models.TextField(default=None, null=True)),
                ('packaging', off_django.models_extensions.ListField(default=None, null=True)),
                ('packaging_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('brands', off_django.models_extensions.ListField(default=None, null=True)),
                ('brands_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('categories', off_django.models_extensions.ListField(default=None, null=True)),
                ('categories_en', off_django.models_extensions.ListField(default=None, null=True)),
                ('categories_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('origins', off_django.models_extensions.ListField(default=None, null=True)),
                ('origins_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('manufacturing_places', off_django.models_extensions.ListField(default=None, null=True)),
                ('manufacturing_places_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('labels', off_django.models_extensions.ListField(default=None, null=True)),
                ('labels_en', off_django.models_extensions.ListField(default=None, null=True)),
                ('labels_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('emb_codes', models.TextField(default=None, null=True)),
                ('emb_codes_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('first_packaging_code_geo', off_django.models_extensions.ListField(default=None, null=True)),
                ('cities', off_django.models_extensions.ListField(default=None, null=True)),
                ('cities_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('purchase_places', off_django.models_extensions.ListField(default=None, null=True)),
                ('stores', off_django.models_extensions.ListField(default=None, null=True)),
                ('countries', off_django.models_extensions.ListField(default=None, null=True)),
                ('countries_en', off_django.models_extensions.ListField(default=None, null=True)),
                ('countries_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('ingredients_text', off_django.models_extensions.ListField(default=None, null=True)),
                ('traces', off_django.models_extensions.ListField(default=None, null=True)),
                ('traces_en', off_django.models_extensions.ListField(default=None, null=True)),
                ('traces_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('additives', off_django.models_extensions.ListField(default=None, null=True)),
                ('additives_en', off_django.models_extensions.ListField(default=None, null=True)),
                ('additives_n', models.IntegerField(default=None, null=True)),
                ('additives_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('allergens', off_django.models_extensions.ListField(default=None, null=True)),
                ('allergens_en', off_django.models_extensions.ListField(default=None, null=True)),
                ('image_small_url', models.TextField(default=None, null=True)),
                ('image_url', models.TextField(default=None, null=True)),
                ('ingredients_from_palm_oil', off_django.models_extensions.ListField(default=None, null=True)),
                ('ingredients_from_palm_oil_n', models.IntegerField(default=None, null=True)),
                ('ingredients_from_palm_oil_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('ingredients_that_may_be_from_palm_oil', off_django.models_extensions.ListField(default=None, null=True)),
                ('ingredients_that_may_be_from_palm_oil_n', models.IntegerField(default=None, null=True)),
                ('ingredients_that_may_be_from_palm_oil_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('main_category', models.TextField(default=None, null=True)),
                ('main_category_en', models.TextField(default=None, null=True)),
                ('no_nutriments', models.TextField(default=None, null=True)),
                ('nutrition_grade_fr', models.CharField(default=None, max_length=1, null=True)),
                ('nutrition_grade_uk', models.CharField(default=None, max_length=1, null=True)),
                ('pnns_groups_1', models.TextField(default=None, null=True)),
                ('pnns_groups_2', models.TextField(default=None, null=True)),
                ('serving_size', models.TextField(default=None, null=True)),
                ('states', off_django.models_extensions.ListField(default=None, null=True)),
                ('states_en', off_django.models_extensions.ListField(default=None, null=True)),
                ('states_tags', off_django.models_extensions.ListField(default=None, null=True)),
                ('_alpha_linolenic_acid_100g', models.FloatField(default=None, null=True)),
                ('_arachidic_acid_100g', models.FloatField(default=None, null=True)),
                ('_arachidonic_acid_100g', models.FloatField(default=None, null=True)),
                ('_behenic_acid_100g', models.FloatField(default=None, null=True)),
                ('_butyric_acid_100g', models.FloatField(default=None, null=True)),
                ('_capric_acid_100g', models.FloatField(default=None, null=True)),
                ('_caproic_acid_100g', models.FloatField(default=None, null=True)),
                ('_caprylic_acid_100g', models.FloatField(default=None, null=True)),
                ('_cerotic_acid_100g', models.FloatField(default=None, null=True)),
                ('_dihomo_gamma_linolenic_acid_100g', models.FloatField(default=None, null=True)),
                ('_docosahexaenoic_acid_100g', models.FloatField(default=None, null=True)),
                ('_eicosapentaenoic_acid_100g', models.FloatField(default=None, null=True)),
                ('_elaidic_acid_100g', models.FloatField(default=None, null=True)),
                ('_erucic_acid_100g', models.FloatField(default=None, null=True)),
                ('_fructose_100g', models.FloatField(default=None, null=True)),
                ('_gamma_linolenic_acid_100g', models.FloatField(default=None, null=True)),
                ('_glucose_100g', models.FloatField(default=None, null=True)),
                ('_gondoic_acid_100g', models.FloatField(default=None, null=True)),
                ('_lactose_100g', models.FloatField(default=None, null=True)),
                ('_lauric_acid_100g', models.FloatField(default=None, null=True)),
                ('_lignoceric_acid_100g', models.FloatField(default=None, null=True)),
                ('_linoleic_acid_100g', models.FloatField(default=None, null=True)),
                ('_maltodextrins_100g', models.FloatField(default=None, null=True)),
                ('_maltose_100g', models.FloatField(default=None, null=True)),
                ('_mead_acid_100g', models.FloatField(default=None, null=True)),
                ('_melissic_acid_100g', models.FloatField(default=None, null=True)),
                ('_montanic_acid_100g', models.FloatField(default=None, null=True)),
                ('_myristic_acid_100g', models.FloatField(default=None, null=True)),
                ('_nervonic_acid_100g', models.FloatField(default=None, null=True)),
                ('_oleic_acid_100g', models.FloatField(default=None, null=True)),
                ('_palmitic_acid_100g', models.FloatField(default=None, null=True)),
                ('_stearic_acid_100g', models.FloatField(default=None, null=True)),
                ('_sucrose_100g', models.FloatField(default=None, null=True)),
                ('alcohol_100g', models.FloatField(default=None, null=True)),
                ('beta_carotene_100g', models.FloatField(default=None, null=True)),
                ('beta_glucan_100g', models.FloatField(default=None, null=True)),
                ('bicarbonate_100g', models.FloatField(default=None, null=True)),
                ('biotin_100g', models.FloatField(default=None, null=True)),
                ('caffeine_100g', models.FloatField(default=None, null=True)),
                ('calcium_100g', models.FloatField(default=None, null=True)),
                ('carbohydrates_100g', models.FloatField(default=None, null=True)),
                ('carbon_footprint_100g', models.FloatField(default=None, null=True)),
                ('carnitine_100g', models.FloatField(default=None, null=True)),
                ('casein_100g', models.FloatField(default=None, null=True)),
                ('chloride_100g', models.FloatField(default=None, null=True)),
                ('chlorophyl_100g', models.FloatField(default=None, null=True)),
                ('cholesterol_100g', models.FloatField(default=None, null=True)),
                ('choline_100g', models.FloatField(default=None, null=True)),
                ('chromium_100g', models.FloatField(default=None, null=True)),
                ('cocoa_100g', models.FloatField(default=None, null=True)),
                ('collagen_meat_protein_ratio_100g', models.FloatField(default=None, null=True)),
                ('copper_100g', models.FloatField(default=None, null=True)),
                ('energy_100g', models.FloatField(default=None, null=True)),
                ('energy_from_fat_100g', models.FloatField(default=None, null=True)),
                ('fat_100g', models.FloatField(default=None, null=True)),
                ('fiber_100g', models.FloatField(default=None, null=True)),
                ('fluoride_100g', models.FloatField(default=None, null=True)),
                ('folates_100g', models.FloatField(default=None, null=True)),
                ('fruits_vegetables_nuts_100g', models.FloatField(default=None, null=True)),
                ('fruits_vegetables_nuts_estimate_100g', models.FloatField(default=None, null=True)),
                ('glycemic_index_100g', models.FloatField(default=None, null=True)),
                ('inositol_100g', models.FloatField(default=None, null=True)),
                ('iodine_100g', models.FloatField(default=None, null=True)),
                ('iron_100g', models.FloatField(default=None, null=True)),
                ('magnesium_100g', models.FloatField(default=None, null=True)),
                ('manganese_100g', models.FloatField(default=None, null=True)),
                ('molybdenum_100g', models.FloatField(default=None, null=True)),
                ('monounsaturated_fat_100g', models.FloatField(default=None, null=True)),
                ('nucleotides_100g', models.FloatField(default=None, null=True)),
                ('nutrition_score_fr_100g', models.FloatField(default=None, null=True)),
                ('nutrition_score_uk_100g', models.FloatField(default=None, null=True)),
                ('omega_3_fat_100g', models.FloatField(default=None, null=True)),
                ('omega_6_fat_100g', models.FloatField(default=None, null=True)),
                ('omega_9_fat_100g', models.FloatField(default=None, null=True)),
                ('pantothenic_acid_100g', models.FloatField(default=None, null=True)),
                ('ph_100g', models.FloatField(default=None, null=True)),
                ('phosphorus_100g', models.FloatField(default=None, null=True)),
                ('phylloquinone_100g', models.FloatField(default=None, null=True)),
                ('polyols_100g', models.FloatField(default=None, null=True)),
                ('polyunsaturated_fat_100g', models.FloatField(default=None, null=True)),
                ('potassium_100g', models.FloatField(default=None, null=True)),
                ('proteins_100g', models.FloatField(default=None, null=True)),
                ('salt_100g', models.FloatField(default=None, null=True)),
                ('saturated_fat_100g', models.FloatField(default=None, null=True)),
                ('selenium_100g', models.FloatField(default=None, null=True)),
                ('serum_proteins_100g', models.FloatField(default=None, null=True)),
                ('silica_100g', models.FloatField(default=None, null=True)),
                ('sodium_100g', models.FloatField(default=None, null=True)),
                ('starch_100g', models.FloatField(default=None, null=True)),
                ('sugars_100g', models.FloatField(default=None, null=True)),
                ('taurine_100g', models.FloatField(default=None, null=True)),
                ('trans_fat_100g', models.FloatField(default=None, null=True)),
                ('vitamin_a_100g', models.FloatField(default=None, null=True)),
                ('vitamin_b12_100g', models.FloatField(default=None, null=True)),
                ('vitamin_b1_100g', models.FloatField(default=None, null=True)),
                ('vitamin_b2_100g', models.FloatField(default=None, null=True)),
                ('vitamin_b6_100g', models.FloatField(default=None, null=True)),
                ('vitamin_b9_100g', models.FloatField(default=None, null=True)),
                ('vitamin_c_100g', models.FloatField(default=None, null=True)),
                ('vitamin_d_100g', models.FloatField(default=None, null=True)),
                ('vitamin_e_100g', models.FloatField(default=None, null=True)),
                ('vitamin_k_100g', models.FloatField(default=None, null=True)),
                ('vitamin_pp_100g', models.FloatField(default=None, null=True)),
                ('water_hardness_100g', models.FloatField(default=None, null=True)),
                ('zinc_100g', models.FloatField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'OFFFood - Model for Open Food Facts food product',
            },
        ),
    ]
